# Generated by Django 5.0 on 2023-12-19 15:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=256, unique=True)),
                ('instantie_type', models.CharField(max_length=256)),
                ('identifier', models.CharField(max_length=1024)),
                ('afkorting', models.CharField(max_length=64)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['naam'], name='rechtspraak_naam_281e92_idx'), models.Index(fields=['instantie_type'], name='rechtspraak_instant_2dabcd_idx'), models.Index(fields=['afkorting'], name='rechtspraak_afkorti_e91ed5_idx'), models.Index(fields=['identifier'], name='rechtspraak_identif_d39691_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rechtsgebied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=512)),
                ('identifier', models.URLField(unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['naam'], name='rechtspraak_naam_b64136_idx')],
            },
        ),
        migrations.CreateModel(
            name='Uitspraak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecli', models.CharField(help_text='The European Case Law Identifier (ECLI) for this Uitspraak.', max_length=128, unique=True)),
                ('zaaknummer', models.CharField(help_text='The case number specific to the Instantie that issued the uitspraak.', max_length=2048)),
                ('publicatiedatum', models.DateField(default=datetime.date(1000, 1, 1))),
                ('uitspraakdatum', models.DateField(default=datetime.date(1000, 1, 1))),
                ('raw_xml', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='JSON field to store optional extra (meta)data.')),
                ('inhoudsindicatie', models.TextField()),
                ('uitspraak', models.TextField()),
                ('instantie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechtspraak.instantie')),
            ],
            options={
                'indexes': [models.Index(fields=['ecli'], name='rechtspraak_ecli_74427c_idx'), models.Index(fields=['zaaknummer'], name='rechtspraak_zaaknum_16cb81_idx'), models.Index(fields=['ecli', 'publicatiedatum'], name='rechtspraak_ecli_9cb2c1_idx'), models.Index(fields=['ecli', 'uitspraakdatum'], name='rechtspraak_ecli_02f69f_idx')],
            },
        ),
    ]
