# Generated by Django 5.0 on 2023-12-07 15:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=256, unique=True)),
                ('instantie_type', models.CharField(max_length=256)),
                ('identifier', models.CharField(max_length=1024)),
                ('afkorting', models.CharField(max_length=64)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uitspraak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecli', models.CharField(max_length=128, unique=True)),
                ('zaaknummer', models.CharField(max_length=2048)),
                ('publicatiedatum', models.DateField(default=datetime.date(1000, 1, 1))),
                ('uitspraakdatum', models.DateField(default=datetime.date(1000, 1, 1))),
                ('raw_xml', models.TextField()),
                ('json', models.JSONField(default=dict)),
                ('inhoudsindicatie', models.TextField()),
                ('uitspraak', models.TextField()),
                ('instantie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechtspraak.instantie')),
            ],
        ),
    ]
