# Generated by Django 5.0 on 2023-12-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechtspraak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureSoort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=512)),
                ('identifier', models.URLField(unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['naam'], name='rechtspraak_naam_825a50_idx')],
            },
        ),
    ]
