# Generated by Django 5.0 on 2023-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechtspraak', '0002_proceduresoort'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitspraak',
            name='procedure_soorten',
            field=models.ManyToManyField(to='rechtspraak.proceduresoort'),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='rechtsgebieden',
            field=models.ManyToManyField(to='rechtspraak.rechtsgebied'),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='uitspraak_type',
            field=models.CharField(choices=[('Uitspraak', 'Uitspraak'), ('Conclusie', 'Conclusie')], default='Uitspraak', max_length=64),
        ),
    ]
