# Generated by Django 5.0.3 on 2024-03-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechtspraak', '0003_uitspraak_procedure_soorten_uitspraak_rechtsgebieden_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uitspraak',
            name='rechtspraak_ecli_9cb2c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='uitspraak',
            name='rechtspraak_ecli_02f69f_idx',
        ),
        migrations.RenameField(
            model_name='uitspraak',
            old_name='uitspraak',
            new_name='tekst',
        ),
        migrations.AddIndex(
            model_name='uitspraak',
            index=models.Index(fields=['instantie', 'publicatiedatum'], name='rechtspraak_instant_203595_idx'),
        ),
        migrations.AddIndex(
            model_name='uitspraak',
            index=models.Index(fields=['instantie', 'uitspraakdatum'], name='rechtspraak_instant_5661b4_idx'),
        ),
        migrations.AddIndex(
            model_name='uitspraak',
            index=models.Index(fields=['uitspraak_type'], name='rechtspraak_uitspra_199431_idx'),
        ),
    ]
